from typing import Protocol

from ..domain.models.state import GameState
from ..domain.models.turn import Turn


class SaveRepository(Protocol):
    def load(self, slug: str) -> GameState | None: ...
    def save(self, slug: str, state: GameState) -> None: ...
    def discard(self, slug: str) -> None: ...


class TraceSink(Protocol):
    def append(self, slug: str, turn: Turn) -> None: ...
    def discard(self, slug: str) -> None: ...
