from typing import Protocol

from ..domain.state import GameState
from ..domain.turn import TraceEntry


class SaveRepository(Protocol):
    def load(self, slug: str) -> GameState | None: ...
    def save(self, slug: str, state: GameState) -> None: ...
    def discard(self, slug: str) -> None: ...


class TraceSink(Protocol):
    def append(self, slug: str, entry: TraceEntry) -> None: ...
    def load(self, slug: str) -> tuple[TraceEntry, ...]: ...
    def discard(self, slug: str) -> None: ...
