"""The domain vocabulary. Grouped in submodules; imported flat as `from ..domain.models import`."""

from ...utils.dice import DiceExpr
from ...utils.models import ABILITIES, Ability, Attributes, Frozen, updated
from .base import (
    PLAYER_ID,
    ROLES,
    SAVE_VERSION,
    EntityId,
    Kind,
    Role,
)
from .consequences import (
    CONSEQUENCE_TYPES,
    ApplyCondition,
    Consequence,
    Damage,
    Discover,
    DropItem,
    GainImprovisedItem,
    GiveItem,
    Heal,
    Magnitude,
    Move,
    References,
    RollCheck,
    TakeItem,
    branches,
    flatten,
)
from .direction import (
    Direction,
)
from .entities import (
    ENTITY_ADAPTER,
    ActorEntity,
    BaseEntity,
    Entity,
    EntityDetail,
    Growth,
    GrowthRequest,
    ItemEntity,
    LocationEntity,
    RejectedGrowth,
    find,
    placement,
)
from .events import (
    CheckRolled,
    ConditionChanged,
    DiceRolled,
    EntityCreated,
    EntityDiscovered,
    Event,
    HpChanged,
    ItemDestination,
    ItemMoved,
    Moved,
)
from .state import (
    CharacterSheet,
    Exchange,
    GameState,
    ScenarioDef,
    ScenarioMeta,
    StartingItem,
    WorldState,
)
from .stats import StatBlock, Wounds
from .turn import Turn  # last: depends on .events, .direction, .state

__all__ = [
    "ABILITIES",
    "ENTITY_ADAPTER",
    "CONSEQUENCE_TYPES",
    "ROLES",
    "SAVE_VERSION",
    "Ability",
    "ActorEntity",
    "ApplyCondition",
    "Attributes",
    "BaseEntity",
    "CharacterSheet",
    "CheckRolled",
    "ConditionChanged",
    "Consequence",
    "Damage",
    "DiceExpr",
    "DiceRolled",
    "Direction",
    "Discover",
    "DropItem",
    "Entity",
    "EntityCreated",
    "EntityDetail",
    "EntityDiscovered",
    "EntityId",
    "Event",
    "Exchange",
    "Frozen",
    "GainImprovisedItem",
    "GameState",
    "GiveItem",
    "Growth",
    "GrowthRequest",
    "Heal",
    "HpChanged",
    "ItemDestination",
    "ItemEntity",
    "ItemMoved",
    "Kind",
    "LocationEntity",
    "Magnitude",
    "Move",
    "Moved",
    "PLAYER_ID",
    "References",
    "RejectedGrowth",
    "RollCheck",
    "Role",
    "ScenarioDef",
    "ScenarioMeta",
    "StartingItem",
    "StatBlock",
    "TakeItem",
    "Turn",
    "WorldState",
    "Wounds",
    "branches",
    "find",
    "flatten",
    "placement",
    "updated",
]
