"""The canonical record models, one module per family. The closed vocabularies they are typed by
are reached through `content.vocabulary`, so each name has exactly one import path."""

from .base import Coin, CoinUnit, Collection, ContentRef, DamageRoll, Record, Slug
from .equipment import (
    ArmorCategory,
    ArmorRecord,
    EquipmentRecord,
    GearRecord,
    MagicItemRecord,
    PackContents,
    Rarity,
    ToolCategory,
    ToolRecord,
    VehicleCategory,
    VehicleRecord,
    WeaponCategory,
    WeaponRange,
    WeaponReach,
    WeaponRecord,
)
from .monsters import (
    AttackType,
    AtWill,
    MonsterAction,
    MonsterAttack,
    MonsterMultiattack,
    MonsterProcedure,
    MonsterRecord,
    MonsterSave,
    MonsterSize,
    MonsterSpell,
    MonsterSpellcasting,
    MonsterType,
    MultiattackOption,
    MultiattackStep,
    PerDay,
    RechargeAfterRest,
    RechargeOnRoll,
    RestType,
    SaveOutcome,
    Senses,
    Speed,
    Usage,
)
from .rules import AlignmentRecord, ConditionRecord, LanguageRecord, SkillRecord, VocabularyRecord
from .spells import SpellAttackType, SpellDamage, SpellRecord, SpellSave, SpellSaveOutcome

__all__ = [
    "AlignmentRecord",
    "ArmorCategory",
    "ArmorRecord",
    "AtWill",
    "AttackType",
    "Coin",
    "CoinUnit",
    "Collection",
    "ConditionRecord",
    "ContentRef",
    "DamageRoll",
    "EquipmentRecord",
    "GearRecord",
    "LanguageRecord",
    "MagicItemRecord",
    "MonsterAction",
    "MonsterAttack",
    "MonsterMultiattack",
    "MonsterProcedure",
    "MonsterRecord",
    "MonsterSave",
    "MonsterSize",
    "MonsterSpell",
    "MonsterSpellcasting",
    "MonsterType",
    "MultiattackOption",
    "MultiattackStep",
    "PackContents",
    "PerDay",
    "Rarity",
    "RechargeAfterRest",
    "RechargeOnRoll",
    "Record",
    "RestType",
    "SaveOutcome",
    "Senses",
    "SkillRecord",
    "Slug",
    "Speed",
    "SpellAttackType",
    "SpellDamage",
    "SpellRecord",
    "SpellSave",
    "SpellSaveOutcome",
    "ToolCategory",
    "ToolRecord",
    "Usage",
    "VehicleCategory",
    "VehicleRecord",
    "VocabularyRecord",
    "WeaponCategory",
    "WeaponRange",
    "WeaponReach",
    "WeaponRecord",
]
