"""The canonical record models, one module per family. The closed vocabularies they are typed by
are reached through `content.vocabulary`, so each name has exactly one import path."""

from collections.abc import Iterator

from .base import (
    Coin,
    CoinUnit,
    Collection,
    ContentRef,
    CreatureSize,
    DamageRoll,
    Record,
    Slug,
)
from .character import (
    AbilityBonus,
    AbilityRequirement,
    BackgroundRecord,
    BonusOption,
    ChoiceEffect,
    ChoiceOption,
    ClassLevelRecord,
    ClassRecord,
    EquipmentProficiency,
    EquipmentProficiencyType,
    FeatRecord,
    FeatureRecord,
    LevelRecord,
    LevelSpellcasting,
    ProficiencyRecord,
    ProgressionChoice,
    RaceRecord,
    RecordOption,
    SaveProficiency,
    SkillProficiency,
    SubclassChoice,
    SubclassLevelRecord,
    SubclassRecord,
    SubraceRecord,
    TraitRecord,
)
from .equipment import (
    ArmorCategory,
    ArmorRecord,
    EquipmentRecord,
    GearRecord,
    MagicItemRecord,
    PackContents,
    Rarity,
    ToolCategory,
    ToolRecord,
    VehicleCategory,
    VehicleRecord,
    WeaponCategory,
    WeaponRange,
    WeaponReach,
    WeaponRecord,
)
from .monsters import (
    AttackType,
    AtWill,
    MonsterAction,
    MonsterAttack,
    MonsterMultiattack,
    MonsterProcedure,
    MonsterRecord,
    MonsterSave,
    MonsterSpell,
    MonsterSpellcasting,
    MonsterType,
    MultiattackOption,
    MultiattackStep,
    PerDay,
    RechargeAfterRest,
    RechargeOnRoll,
    RestType,
    SaveOutcome,
    Senses,
    Speed,
    Usage,
)
from .rules import AlignmentRecord, ConditionRecord, LanguageRecord, SkillRecord, VocabularyRecord
from .spells import SpellAttackType, SpellDamage, SpellRecord, SpellSave, SpellSaveOutcome

__all__ = [
    "AbilityBonus",
    "AbilityRequirement",
    "AlignmentRecord",
    "ArmorCategory",
    "ArmorRecord",
    "AtWill",
    "AttackType",
    "BackgroundRecord",
    "BonusOption",
    "ChoiceEffect",
    "ChoiceOption",
    "ClassLevelRecord",
    "ClassRecord",
    "Coin",
    "CoinUnit",
    "Collection",
    "ConditionRecord",
    "ContentRef",
    "CreatureSize",
    "DamageRoll",
    "EquipmentProficiency",
    "EquipmentProficiencyType",
    "EquipmentRecord",
    "FeatRecord",
    "FeatureRecord",
    "GearRecord",
    "LanguageRecord",
    "LevelRecord",
    "LevelSpellcasting",
    "MagicItemRecord",
    "MonsterAction",
    "MonsterAttack",
    "MonsterMultiattack",
    "MonsterProcedure",
    "MonsterRecord",
    "MonsterSave",
    "MonsterSpell",
    "MonsterSpellcasting",
    "MonsterType",
    "MultiattackOption",
    "MultiattackStep",
    "PackContents",
    "PerDay",
    "ProficiencyRecord",
    "ProgressionChoice",
    "RaceRecord",
    "Rarity",
    "RechargeAfterRest",
    "RechargeOnRoll",
    "Record",
    "RecordOption",
    "RestType",
    "SaveOutcome",
    "SaveProficiency",
    "Senses",
    "SkillProficiency",
    "SkillRecord",
    "Slug",
    "Speed",
    "SpellAttackType",
    "SpellDamage",
    "SpellRecord",
    "SpellSave",
    "SpellSaveOutcome",
    "SubclassChoice",
    "SubclassLevelRecord",
    "SubclassRecord",
    "SubraceRecord",
    "ToolCategory",
    "ToolRecord",
    "TraitRecord",
    "Usage",
    "VehicleCategory",
    "VehicleRecord",
    "VocabularyRecord",
    "WeaponCategory",
    "WeaponRange",
    "WeaponReach",
    "WeaponRecord",
]


def _shipped(record: type[Record]) -> Iterator[type[Record]]:
    """The record classes a pack ships: a class nothing extends. Everything above one — `Record`,
    `EquipmentRecord`, `VocabularyRecord` — is shared shape, and no collection holds it."""
    subclasses = record.__subclasses__()
    for subclass in subclasses:
        yield from _shipped(subclass)
    if not subclasses:
        yield record


# Checked here because every record module is imported above; see `Record` for why at all.
if _undeclared := sorted(r.__name__ for r in _shipped(Record) if not hasattr(r, "COLLECTION")):
    raise TypeError(f"record classes declaring no COLLECTION: {_undeclared}")
