from collections.abc import Sequence
from random import Random
from typing import Protocol

from pydantic import BaseModel

from aidm.kernel.envelope import CharacterEnvelope
from aidm.kernel.views import CreationPreview, Views
from aidm.state.creation import CreationStep, Picks
from aidm.state.entities import EngineId, Slug
from aidm.state.facts import Fact
from aidm.state.model import Character, Game, Scenario
from aidm.state.play import DecisionOption, PendingOption
from aidm.state.tools import MasterTool


class EngineIdentity(Protocol):
    """All content loading needs of an engine: which rules a file has to be written for."""

    @property
    def id(self) -> EngineId: ...


class Creation(Protocol):
    def steps(self, picks: Picks) -> tuple[CreationStep, ...]: ...
    def created(
        self, name: str, brief: str, picks: Picks
    ) -> tuple[CharacterEnvelope, CreationPreview]: ...


class Engine[S: BaseModel](Protocol):
    """Properties, not attributes: only a read-only member accepts a frozen dataclass field."""

    @property
    def id(self) -> EngineId: ...
    @property
    def title(self) -> str: ...
    @property
    def instructions(self) -> str: ...
    @property
    def tools(self) -> tuple[MasterTool, ...]: ...
    @property
    def creation(self) -> Creation: ...
    @property
    def packs(self) -> tuple[DecisionOption, ...]: ...
    def new_game(self, scenario: Scenario, character: Character, /) -> S: ...
    def guidance(self, packs: Sequence[Slug], /) -> str: ...
    def restored(self, raw: str, /) -> Game: ...
    def validate(self, state: Game, /) -> None: ...
    def views(self, state: Game, /) -> Views: ...
    def answer(self, draft: Game, chosen: PendingOption, rng: Random, /) -> tuple[Fact, ...]: ...
    def over(self, state: Game, /) -> str | None: ...
    def scene_closed(self, draft: Game, /) -> tuple[Fact, ...]: ...
